# Generated by Django 5.1.5 on 2025-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
