# Generated by Django 5.1.5 on 2025-02-02 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_alter_myaccount_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
